const mongoose = require("mongoose");
const genres = require("../utils/ott");

const movieSchema = mongoose.Schema(
  {
    name: {type: String,},
    engname: {type: String,},
    dramalink: {type: String,trim: true,unique:true},
    category: {type: String,},
    moviePoster: {type: String},
    releasedate: {type: String,trim: true,},
    episodeEndDate: {type: String,trim: true,},
    episodeEndDateStamp: {type: Number,trim: true,},
    releaseDate: {type: Number,trim: true,},
    year: {type: Number,trim: true,},
    readmorestory: {type: String,trim: true,},
    director: {type: String,trim: true,},
    directorlink: {type: String,trim: true,},
    producedby: {type: String,trim: true,},
    producedbylink: {type: String,trim: true,},
    written: {type: String,trim: true,},
    writtenlink: {type: String,trim: true,},
    genre: { type: [String],trim: true,},
    duration: {type: String,trim: true,},
    story: {type: String,trim: true,},
    images: {type: [String]},
    storyenglish:{type: String,trim: true,},
    ytlink:{type: String,trim: true,},
    whereToWatch:{
        type: Object,
        ottName: { type: String },
        ottImg: { type: String },
        ottUrl: {type:String},
    },
    tags: { type: [String],trim: true,},
    episodes: {type: Number,trim: true,},
    country: {type: String,trim:true},
    twitCode: { type: [String],trim: true,},
    twitLink: { type: [String],trim: true,},
    actid1: {type: String,trim: true,},
    actid2: {type: String,trim: true,},
    actid3: {type: String,trim: true,},
    actid4: {type: String,trim: true,},
    actid5: {type: String,trim: true,},
    actid6: {type: String,trim: true,},
    actid7: {type: String,trim: true,},
    actorname1: {type: String,trim: true,},
    actorname2: {type: String,trim: true,},
    actorname3: {type: String,trim: true,},
    actorname4: {type: String,trim: true,},
    actorname5: {type: String,trim: true,},
    actorname6: {type: String,trim: true,},
    actorname7: {type: String,trim: true,},
    mvactorname1: {type: String,trim: true,},
    mvactorname2: {type: String,trim: true,},
    mvactorname3: {type: String,trim: true,},
    mvactorname4: {type: String,trim: true,},
    mvactorname5: {type: String,trim: true,},
    mvactorname6: {type: String,trim: true,},
    mvactorname7: {type: String,trim: true,},
    actimg1: {type: String,trim: true,},
    actimg2: {type: String,trim: true,},
    actimg3: {type: String,trim: true,},
    actimg4: {type: String,trim: true,},
    actimg5: {type: String,trim: true,},
    actimg6: {type: String,trim: true,},
    actimg7: {type: String,trim: true,},
    celeblink1:{type: String,trim: true,},
    celeblink2:{type: String,trim: true,},
    celeblink3:{type: String,trim: true,},
    celeblink4:{type: String,trim: true,},
    celeblink5:{type: String,trim: true,},
    celeblink6:{type: String,trim: true,},
    celeblink7:{type: String,trim: true,},
    celebrole1:{type: String,trim: true,},
    celebrole2:{type: String,trim: true,},
    celebrole3:{type: String,trim: true,},
    celebrole4:{type: String,trim: true,},
    celebrole5:{type: String,trim: true,},
    celebrole6:{type: String,trim: true,},
    celebrole7:{type: String,trim: true,},

  },
  { timestamps: true }
);

module.exports = mongoose.model("Movie", movieSchema);